export const PDF_FIELD_MAP = {
  propertyAddress: { pdfName: 'Property Address', type: 'text' },
  homesteadExemption: { pdfName: 'Homestead', type: 'checkbox' },
  homesteadAmount: { pdfName: 'Homestead $', type: 'text' },
  veteransExemption: { pdfName: 'Veterans', type: 'checkbox' },
  veteransAmount: { pdfName: 'Veterans $', type: 'text' },
  treeGrowthExemption: { pdfName: 'Tree Growth', type: 'checkbox' },
  treeGrowthAmount: { pdfName: 'Tree Growth $', type: 'text' },
  noExemptions: { pdfName: 'NA', type: 'checkbox' },
  propertyDataCard: { pdfName: 'undefined', type: 'checkbox' },
  taxMap: { pdfName: 'undefined_2', type: 'checkbox' },
  dateVisited: { pdfName: 'DATE VISITED', type: 'date' },
  currentZoning: { pdfName: 'Current Zone', type: 'text' },
  zoningOverlay: { pdfName: 'Overlay?', type: 'text' },
  floodZone: { pdfName: 'Flood Zone', type: 'radio' },
  conformsToZoning: {
    pdfName: '2 Does current use appear to conform to zoning restrictions',
    type: 'text',
  },
  dwellingUnits: {
    pdfName: '3 Number of legal dwelling units permitted per ordinance',
    type: 'text',
  },
  septicInShoreland: {
    yes: 'undefined_3',
    no: 'undefined_4',
    na: 'undefined_5',
    type: 'radio-checkboxes',
  },
  permitsDescription: {
    pdfName:
      '5 Record dates  descriptions of permits issued or code enforcement issues if any DO NOT LEAVE BLANK',
    type: 'text',
  },
  codeEnforcementDocs: { pdfName: 'toggle_12', type: 'checkbox' },
  zoneOverlays: { pdfName: 'undefined_6', type: 'checkbox' },
  recordedSurvey: { pdfName: 'undefined_7', type: 'checkbox' },
  easements: { pdfName: 'undefined_8', type: 'checkbox' },
  associationDocs: { pdfName: 'undefined_9', type: 'checkbox' },
  associationFinancials: { pdfName: 'undefined_10', type: 'checkbox' },
  condoCertificate: { pdfName: 'undefined_11', type: 'checkbox' },
  septicDesign: { pdfName: 'undefined_12', type: 'checkbox' },
  completedBy: { pdfName: '4 COMPLETED BY', type: 'text' },
};

export const DEFAULT_FORM_DATA = {
  propertyAddress: '',
  homesteadExemption: false,
  homesteadAmount: '',
  veteransExemption: false,
  veteransAmount: '',
  treeGrowthExemption: false,
  treeGrowthAmount: '',
  noExemptions: false,
  propertyDataCard: false,
  taxMap: false,
  dateVisited: '',
  currentZoning: '',
  floodZone: '',
  zoningOverlay: '',
  conformsToZoning: '',
  dwellingUnits: '',
  septicInShoreland: '',
  permitsDescription: '',
  codeEnforcementDocs: false,
  zoneOverlays: false,
  recordedSurvey: false,
  easements: false,
  associationDocs: false,
  associationFinancials: false,
  condoCertificate: false,
  septicDesign: false,
  completedBy: '',
  attachments: [],
};
